services:
  base-python:
    build:
      context: .
      dockerfile: ./common/Dockerfile
    image: langmlops/base-python:latest
  
  frontend:
    build: ./airflow/dags/frontend
    env_file:
      - .env
    ports:
      - 8501:8501
    depends_on:
      - base-python
      - backend
    volumes:
      - ./airflow/dags/frontend:/app
    networks:
      - app
    container_name: frontend
  
  backend:
    build: ./airflow/dags/backend
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - base-python
    volumes:
      - ./airflow/dags/backend:/app
    networks:
      - app
    container_name: backend
  
  airflow:
    build: airflow
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - base-python
      - backend
    networks:
      - app
    volumes:
      - ./airflow/dags:/app/airflow/dags
      - ./airflow/logs:/app/airflow/logs
      - ./airflow/plugins:/app/airflow/plugins
      - ./airflow/scripts:/app

    entrypoint:  
      - /bin/sh
      - /app/entrypoint.sh
    container_name: airflow

networks:
  app:
    driver: bridge