services:
  base-python:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: langmlops/base-python:latest

  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
     - base-python
     - backend
    volumes:
     - ./frontend:/app
    networks:
     - app
    container_name: frontend

  backend:
    build: backend
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - base-python
    volumes:
      - ./backend:/app
    networks:
      - app
    container_name: backend

  airflow:
    build: airflow
    env_file:
      - .env
    entrypoint: ['/entrypoint.sh']
    ports:
      - 8080:8080
    depends_on:
      - base-python
      - ./backend:/app
    networks:
      - app
    volumes:
      - ./airflow/dags:${AIRFLOW_HOME}/dags
      - ./airflow/logs:${AIRFLOW_HOME}/logs
      - ./airflow/pluins:${AIRFLOW_HOME}/plugins
    container_name: airflow

networks:
  app:
    driver: bridge
