FROM apache/airflow:slim-2.10.5-python3.11

COPY requirements.txt app/requirements.txt

ARG AIRFLOW_VAR_DB_USERNAME = 'username'

ARG AIRFLOW_VAR_DB_PASSWORD = 'password'

ARG AIRFLOW_USER = 'Gominho'

ARG AIRFLOW_FIRSTNAME = 'Matheus'

ARG AIRFLOW_LASTNAME = 'Gominho'

ARG AIRFLOW_ROLE = 'Admin'

ARG AIRFLOW_PASSWORD = 'password'

WORKDIR /app

